name: E2E (Android)

on:
  push:
    branches: [main]

jobs:
  build:
    name: E2E (Android)
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install

      - name: Install Java JDK
        uses: joschi/setup-jdk@v1
        with:
          java-version: "openjdk8"
          architecture: "x64"
        env:
          # https://github.com/actions/toolkit/issues/641#issuecomment-728963957
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Build for e2e
        run: yarn build:android-release

      - name: Run e2e
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel
          avd-name: Pixel_3a_API_30
          script: yarn test:android-release

      - name: Store Detox artifacts on test failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: detox-artifacts
          path: .artifacts
